server:
  port: 7777

spring:
  output:
    ansi:
      enabled: always
  file-upload:
    upload-dir: /upload
  jwt:
    secret: bWluc2Vva21pbnNlb2ttaW5zZW9rbWluc2Vva21pbnNlb2s=
    expiration: 3600000

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/erp_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MyHikariPool
      auto-commit: true
      connection-test-query: SELECT 1

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
  config-location: classpath:/mybatis-config.xml